---
title: Jeff Chausse
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jchausse@gmail.com
description: 'Jeff Chausse is a Boston-area User Experience designer with over 15
  years experience designing websites and mobile apps.

'
baseurl: 
url: http://www.jeffchausse.com
twitter_username: jeffchausse
github_username: jchausse
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- server.js
- package.json
- fp-jekyll.sublime-project
- node_modules
